name: Build Wheels

on:
  push:
    branches:
      - main  # ou 'master', conforme seu branch principal
    tags:
      - 'v*'  # Executa quando uma tag como v0.1.0 é criada
  pull_request:
    branches:
      - main  # ou 'master'
  workflow_dispatch:  # Permite acionar manualmente pela interface do GitHub Actions

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Não cancela outros jobs se um falhar
      matrix:
        # Defina os sistemas operacionais desejados
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Defina as versões Python em formato CPython (cp39, cp310, etc.)
        python-version: ['cp39', 'cp310', 'cp311', 'cp312']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para buscar tags e histórico para versionamento, se necessário

      - name: Set up QEMU (for Linux ARM builds - opcional)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all  # Ou especifique 'arm64' se só precisar disso

      - name: Install Fortran compiler (OS specific)
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update -y -qq
            sudo apt-get install -y gfortran
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            # Instala o gcc via Homebrew. O gcc inclui o gfortran,
            # porém o executável pode estar nomeado como gfortran-<versão>
            brew install gcc || true
            # Adiciona o diretório de binários do Homebrew à variável PATH
            echo "$(brew --prefix)/bin" >> $GITHUB_PATH
            # Se não existir 'gfortran' direto, cria um symlink para o primeiro binário encontrado
            if [ ! -x /opt/homebrew/bin/gfortran ]; then
              for file in /opt/homebrew/bin/gfortran-* ; do
                ln -s "$file" /opt/homebrew/bin/gfortran
                echo "Criado symlink para: $file -> /opt/homebrew/bin/gfortran"
                break
              done
            fi
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            # Nos runners do Windows, o ambiente MSYS2/MinGW-w64 já está instalado
            # Adiciona o diretório do mingw64 ao PATH
            echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
            # Verifica a instalação (opcional)
            gfortran --version
          fi

      # A etapa de setup-python é utilizada para rodar o cibuildwheel
      - name: Set up Python (for cibuildwheel)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Uma versão Python para executar o cibuildwheel

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.*

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Define quais builds serão feitos (usando a versão Python selecionada na matrix)
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          # Comando a ser executado ANTES do build para instalar dependências necessárias (como numpy)
          CIBW_BEFORE_BUILD: "pip install numpy"
          # Configurações específicas para as imagens manylinux no Linux (ajuste conforme necessário)
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          # Verbosidade para debug
          CIBW_BUILD_VERBOSITY: "1"
          # No Windows, garante que o compilador MinGW-w64 (que contém o gfortran) esteja no PATH
          CIBW_ENVIRONMENT_WINDOWS: 'PATH="$PATH:/c/msys64/mingw64/bin"'

      - name: Upload wheels as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl
