name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Selecionamos versões do Python superiores a 3.9
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Instalar compiladores Fortran, se necessário
      - name: Instalar dependências do sistema (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran

      - name: Instalar dependências do sistema (macOS)
        if: runner.os == 'macOS'
        run: brew install gcc  # O gcc no macOS inclui o gfortran

      - name: Instalar dependências do sistema (Windows)
        if: runner.os == 'Windows'
        run: choco install mingw  # Alternativamente, configure seu ambiente via MSYS2

      - name: Instalar cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Construir as wheels
        run: cibuildwheel --output-dir wheelhouse .

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
